apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-lanchonete-55
  labels:
    app: api-lanchonete-55
spec:
  template:
    metadata:
      name: api-lanchonete-55
      labels:
        app: api-lanchonete-55
    spec:
      containers:
        - name: api-lanchonete-55-container
          image: gabrielaranda/lanchonete-55-api:kubernetes-config
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          env:
            - name: DB_HOST
              value: "db-lanchonete-55-service"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_DATABASE
              value: "lanchonete-55"
            - name: DB_PORT
              value: "3306"
  replicas: 1
  selector:
    matchLabels:
      app: api-lanchonete-55
