name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get branch name
      shell: bash
      id: get_branch_name
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
    #     aws-region: "us-east-1"
    
    - name: Build Docker image
      run: docker build -t lanchonete-55:${{ env.BRANCH_NAME }} .

    - name: Login to AWS ECR and push Docker image
      if: github.ref == 'refs/heads/main'
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_ACCESS_KEY }}
        aws configure set default.region us-east-1
        
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_URI }}
        
        docker tag lanchonete-55:${{ env.BRANCH_NAME }} ${{ env.ECR_URI }}/${{ env.BRANCH_NAME }}
        docker push ${{ env.ECR_URI }}/${{ env.BRANCH_NAME }}